apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["bilbomd/backend"]'
  name: backend-loadbalancer
  namespace: bilbomd
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 5432tcp
    port: 5432
    protocol: TCP
    targetPort: 3500
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-bilbomd-backend
  sessionAffinity: None
  type: LoadBalancer

