apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["bilbomd/mongo"]'
  name: mongo
  namespace: bilbomd
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 27017tcp
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-bilbomd-mongo
  sessionAffinity: None
  type: ClusterIP

