apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    field.cattle.io/description: BilboMD Backend App
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-{{ .Values.namespace }}-{{ .Values.backend.name }}
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-{{ .Values.namespace }}-{{ .Values.backend.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-{{ .Values.namespace }}-{{ .Values.backend.name }}
    spec:
      affinity: {}
      containers:
      - envFrom:
        - configMapRef:
            name: {{ .Values.backend.name }}-config
            optional: false
        - secretRef:
            name: {{ .Values.backend.name }}-secrets
            optional: false
        - secretRef:
            name: sfapi-priv-key
            optional: false
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        name: container-0
        ports:
        - containerPort: 3500
          name: 3500tcp
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - DAC_OVERRIDE
            - FOWNER
            - NET_BIND_SERVICE
            - SETGID
            - SETUID
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsUser: 62704
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /bilbomd/uploads-spin
          name: vol-bilbomd-uploads
        - mountPath: /secrets
          name: vol-sfapi-priv-key
        - mountPath: /bilbomd/uploads
          name: vol-uploads
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-nersc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 104818
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol-bilbomd-uploads
        persistentVolumeClaim:
          claimName: bilbomd-uploads
      - name: vol-sfapi-priv-key
        secret:
          defaultMode: 420
          secretName: sfapi-priv-key
      - hostPath:
          path: /global/cfs/cdirs/m4521/bilbomd-uploads
          type: Directory
        name: vol-uploads
