apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
  name: ingress
  namespace: bilbomd
spec:
  rules:
  - host: ingress.bilbomd.development.svc.spin.nersc.org
    http:
      paths:
      - backend:
          service:
            name: ui
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: bilbomd-nersc.bl1231.als.lbl.gov
    http:
      paths:
      - backend:
          service:
            name: ui
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - bilbomd-nersc.bl1231.als.lbl.gov
    secretName: ui-tls

