apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    field.cattle.io/description: BilboMD Worker App
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-{{ .Values.namespace }}-{{ .Values.worker.name }}
  name: "{{ .Values.worker.name }}"
  namespace: "{{ .Values.namespace }}"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-{{ .Values.namespace }}-{{ .Values.worker.name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-{{ .Values.namespace }}-{{ .Values.worker.name }}
    spec:
      affinity: {}
      containers:
      - envFrom:
        - configMapRef:
            name: {{ .Values.namespace }}-config
            optional: false
        - secretRef:
            name: sfapi-priv-key
            optional: false
        - secretRef:
            name: {{ .Values.namespace }}-secrets
            optional: false
        image: "{{ .Values.docker_registry }}/{{ .Values.nersc_repo }}/{{ .Values.worker.image.repository }}:{{ .Values.worker.image.tag }}"
        imagePullPolicy: "{{ .Values.worker.image.pullPolicy }}"
        name: container-0
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: false
          runAsUser: 62704
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /secrets
          name: vol-sfapi-priv-key
        - mountPath: /bilbomd/uploads
          name: vol-uploads
        - mountPath: /bilbomd/logs
          name: vol-logs
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-nersc
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 104818
      terminationGracePeriodSeconds: 30
      volumes:
      - name: vol-sfapi-priv-key
        secret:
          defaultMode: 420
          secretName: sfapi-priv-key
      - hostPath:
          path: /global/cfs/cdirs/{{ .Values.nersc_repo }}/bilbomd-uploads
          type: Directory
        name: vol-uploads
      - hostPath:
          path: /global/cfs/cdirs/{{ .Values.nersc_repo }}/{{ .Values.logs.worker }}
          type: Directory
        name: vol-logs
