ingress:
  host: 'ingress.bilbomd.development.svc.spin.nersc.org'
  fqdn: 'bilbomd-nersc-dev.bl1231.als.lbl.gov'
  secret: 'ui-tls-dev'

bilbomd:
  url: 'https://bilbomd-nersc-dev.bl1231.als.lbl.gov'

env:
  NODE_ENV: 'development'
  BILBOMD_ENV: 'development'

auth:
  orcid_issuer: 'https://sandbox.orcid.org'
  orcid_client_id: 'APP-X9112LN3N2ZS1ATI'
  orcid_redirect_uri: 'https://bilbomd-nersc-dev.bl1231.als.lbl.gov/api/v1/auth/orcid/callback'

logs:
  backend: 'bilbomd/dev/logs/backend'
  worker: 'bilbomd/dev/logs/worker'
  ui: 'bilbomd/dev/logs/ui'

backups: 'bilbomd/dev/backups'

scripts: 'bilbomd/dev/scripts'

uploads: 'bilbomd/dev/uploads'

working_dir: 'bilbomd/dev/'

mongo:
  name: mongo
  image:
    repository: mongo
    tag: 7.0.24
    pullPolicy: IfNotPresent
    secret: registry-nersc
  config:
    MONGO_INITDB_ROOT_USERNAME: 'bilbomd-backend-user'

redis:
  name: redis
  image:
    repository: redis
    tag: 7.4.5
    pullPolicy: Always
    secret: registry-nersc

ui:
  name: ui
  image:
    registry: ghcr.io
    owner: bl1231
    user: null
    repository: bilbomd-ui
    build: null
    tag: 1.22.2
    pullPolicy: Always
    secret: ghcr

backend:
  name: backend
  image:
    registry: ghcr.io
    owner: bl1231
    user: null
    repository: bilbomd-backend
    build: null
    tag: pr-89-c5a8d125
    pullPolicy: Always
    secret: ghcr

worker:
  name: worker
  image:
    registry: ghcr.io
    owner: bl1231
    user: null
    repository: bilbomd-worker
    build: null
    tag: 1.18.2
    pullPolicy: Always
    secret: ghcr
