ingress:
  host: "ingress.bilbomd.production.svc.spin.nersc.org"
  fqdn: "bilbomd-nersc.bl1231.als.lbl.gov"
  secret: "ui-tls"

bilbomd:
  url: "https://bilbomd-nersc.bl1231.als.lbl.gov"

env:
  NODE_ENV: "production"
  BILBOMD_ENV: "production"

logs:
  backend: "bilbomd/prod/logs/backend"
  worker: "bilbomd/prod/logs/worker"
  ui: "bilbomd/prod/logs/ui"

backups: "bilbomd/prod/backups"

scripts: "bilbomd/prod/scripts"

uploads: "bilbomd/prod/uploads"

working_dir: "bilbomd/prod/"

redis:
  name: redis
  image:
    repository: redis
    tag: 7.4.0
    pullPolicy: Always
    secret: registry-nersc

ui:
  name: ui
  image:
    registry: ghcr.io
    owner: bl1231
    user: null
    repository: bilbomd-ui
    build: null
    tag: 1.10.3
    pullPolicy: Always
    secret: ghcr
  mode: "production"

backend:
  name: backend
  image:
    registry: ghcr.io
    owner: bl1231
    user: null
    repository: bilbomd-backend
    build: bilbomd-backend
    tag: 1.10.2
    pullPolicy: Always
    secret: ghcr

worker:
  name: worker
  image:
    registry: ghcr.io
    owner: bl1231
    user: null
    repository: bilbomd-worker
    build: bilbomd-worker
    tag: 1.7.0
    pullPolicy: Always
    secret: ghcr
