namespace: bilbomd

docker_registry: registry.nersc.gov
nersc_repo: m4659

cfs_dir: /global/cfs/cdirs

sfapi:
  token_expires: "2024-09-05 23:30"

mongo:
  name: mongo
  image:
    repository: mongo
    tag: 7.0.12
    pullPolicy: IfNotPresent
    secret: registry-nersc
  config:
    MONGO_INITDB_ROOT_USERNAME: "bilbomd-backend-user"

redis:
  name: redis
  image:
    repository: redis
    tag: 7.2.5
    pullPolicy: IfNotPresent
    secret: registry-nersc
