namespace: bilbomd

docker_registry: registry.nersc.gov
nersc_repo: m4659

cfs_dir: /global/cfs/cdirs

pscratch: /pscratch/sd/s/sclassen

sfapi:
  token_expires: "2024-11-09 16:24"

mongo:
  name: mongo
  image:
    repository: mongo
    tag: 7.0.14
    pullPolicy: IfNotPresent
    secret: registry-nersc
  config:
    MONGO_INITDB_ROOT_USERNAME: "bilbomd-backend-user"
