namespace: bilbomd

mongo:
  name: mongo
  image:
    repository: mongo
    tag: "7.0.6"
    pullPolicy: IfNotPresent
  config:
    MONGO_INITDB_ROOT_USERNAME: "bilbomd-backend-user"

redis:
  name: redis
  image:
    repository: redis
    tag: "7.2.4"
    pullPolicy: IfNotPresent

backend:
  name: backend
  image:
    repository: registry.nersc.gov/m4521/sclassen/bilbomd-backend
    tag: "latest"
    pullPolicy: Always

ui:
  name: ui
  image:
    repository: registry.nersc.gov/m4521/sclassen/bilbomd-ui
    tag: "latest"
    pullPolicy: Always
