ingress:
  host: "ingress.bilbomd.production.svc.spin.nersc.org"
  fqdn: "bilbomd-nersc.bl1231.als.lbl.gov"
  secret: "ui-tls"

bilbomd:
  url: "https://bilbomd-nersc.bl1231.als.lbl.gov"

env:
  NODE_ENV: "production"

logs:
  backend: "bilbomd/prod/logs/backend"
  worker: "bilbomd/prod/logs/worker"
  ui: "bilbomd/prod/logs/ui"

uploads: "bilbomd/prod/uploads"

scripts: "bilbomd/prod/scripts"

ui:
  name: ui
  image:
    registry: ghcr.io
    owner: bl1231
    user: null
    repository: bilbomd-ui
    build: null
    tag: "latest"
    pullPolicy: Always
    secret: ghcr

backend:
  name: backend
  image:
    registry: ghcr.io
    owner: bl1231
    user: null
    repository: bilbomd-backend
    build: bilbomd-spin-backend
    tag: "latest"
    pullPolicy: Always
    secret: ghcr

worker:
  name: worker
  image:
    registry: ghcr.io
    owner: bl1231
    user: null
    repository: bilbomd-worker
    build: bilbomd-spin-worker
    tag: "latest"
    pullPolicy: Always
    secret: ghcr
