namespace: bilbomd

docker_registry: registry.nersc.gov
nersc_repo: m4659

mongo:
  name: mongo
  image:
    repository: mongo
    tag: "7.0.9"
    pullPolicy: IfNotPresent
  config:
    MONGO_INITDB_ROOT_USERNAME: "bilbomd-backend-user"

redis:
  name: redis
  image:
    repository: redis
    tag: "7.2.5"
    pullPolicy: IfNotPresent

backend:
  name: backend
  image:
    repository: sclassen/bilbomd-spin-backend
    tag: "latest"
    pullPolicy: Always

ui:
  name: ui
  image:
    repository: sclassen/bilbomd-ui
    tag: "latest"
    pullPolicy: Always

worker:
  name: worker
  image:
    repository: sclassen/bilbomd-spin-worker
    tag: "latest"
    pullPolicy: Always
