ingress:
  host: "ingress.bilbomd.development.svc.spin.nersc.org"
  fqdn: "bilbomd-nersc-dev.bl1231.als.lbl.gov"
  secret: "ui-tls-dev"

bilbomd:
  url: "https://bilbomd-nersc-dev.bl1231.als.lbl.gov"

logs:
  backend: "bilbomd/dev/logs/backend"
  worker: "bilbomd/dev/logs/worker"

uploads: "bilbomd/dev/uploads"

ui:
  name: ui
  image:
    registry: ghcr.io
    owner: bl1231
    user: null
    repository: bilbomd-ui
    build: null
    tag: "latest"
    pullPolicy: Always
    secret: ghcr

backend:
  name: backend
  image:
    registry: ghcr.io
    owner: bl1231
    user: null
    repository: bilbomd-backend
    build: bilbomd-spin-backend
    tag: "latest"
    pullPolicy: Always
    secret: ghcr

worker:
  name: worker
  image:
    registry: ghcr.io
    owner: bl1231
    user: null
    repository: bilbomd-worker
    build: bilbomd-spin-worker
    tag: "latest"
    pullPolicy: Always
    secret: ghcr
