ingress:
  host: "ingress.bilbomd.production.svc.spin.nersc.org"
  fqdn: "bilbomd-nersc.bl1231.als.lbl.gov"
  secret: "ui-tls"

bilbomd:
  url: "https://bilbomd-nersc.bl1231.als.lbl.gov"

env:
  NODE_ENV: "production"
  BILBOMD_ENV: "production"

auth:
  orcid_issuer: "https://orcid.org"
  orcid_client_id: "APP-XXXXXXXXXX" # Replace with your actual ORCID client ID
  orcid_redirect_uri: "https://bilbomd-nersc.bl1231.als.lbl.gov/api/v1/auth/orcid/callback"

logs:
  backend: "bilbomd/prod/logs/backend"
  worker: "bilbomd/prod/logs/worker"
  ui: "bilbomd/prod/logs/ui"

backups: "bilbomd/prod/backups"

scripts: "bilbomd/prod/scripts"

uploads: "bilbomd/prod/uploads"

working_dir: "bilbomd/prod/"

mongo:
  name: mongo
  image:
    repository: mongo
    tag: 7.0.19
    pullPolicy: IfNotPresent
    secret: registry-nersc
  config:
    MONGO_INITDB_ROOT_USERNAME: "bilbomd-backend-user"

redis:
  name: redis
  image:
    repository: redis
    tag: 7.4.2
    pullPolicy: Always
    secret: registry-nersc

ui:
  name: ui
  image:
    registry: ghcr.io
    owner: bl1231
    user: null
    repository: bilbomd-ui
    build: null
    tag: 1.21.3
    pullPolicy: Always
    secret: ghcr

backend:
  name: backend
  image:
    registry: ghcr.io
    owner: bl1231
    user: null
    repository: bilbomd-backend
    build: null
    tag: 1.21.1
    pullPolicy: Always
    secret: ghcr

worker:
  name: worker
  image:
    registry: ghcr.io
    owner: bl1231
    user: null
    repository: bilbomd-worker
    build: null
    tag: 1.15.2
    pullPolicy: Always
    secret: ghcr
